# Generated by Django 6.0.1 on 2026-04-17 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('country_code', models.CharField(default='ZM', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Creator bio or description')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='creator_profiles/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='creator_covers/')),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active', max_length=20)),
                ('followers_count', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rating', models.FloatField(default=5.0, help_text='Creator rating from 0 to 5', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('verified', models.BooleanField(default=False, help_text='Verified creator badge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('x_profile', models.URLField(blank=True, help_text='X (Twitter) profile URL', validators=[django.core.validators.URLValidator()])),
                ('instagram_profile', models.URLField(blank=True, help_text='Instagram profile URL', validators=[django.core.validators.URLValidator()])),
                ('youtube_profile', models.URLField(blank=True, help_text='YouTube channel URL', validators=[django.core.validators.URLValidator()])),
                ('tikTok_profile', models.URLField(blank=True, help_text='TikTok profile URL', validators=[django.core.validators.URLValidator()])),
                ('facebook_profile', models.URLField(blank=True, help_text='Facebook profile URL', validators=[django.core.validators.URLValidator()])),
                ('categories', models.ManyToManyField(blank=True, related_name='creators', to='creators.creatorcategory')),
            ],
            options={
                'verbose_name': 'Creator Profile',
                'verbose_name_plural': 'Creator Profiles',
                'db_table': 'creators_profile',
                'ordering': ['-followers_count'],
            },
        ),
    ]
