# Generated by Django 6.0.1 on 2026-01-28 18:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Creator bio or description')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='creator_profiles/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='creator_covers/')),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active', max_length=20)),
                ('followers_count', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rating', models.FloatField(default=5.0, help_text='Creator rating from 0 to 5', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('verified', models.BooleanField(default=False, help_text='Verified creator badge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creator Profile',
                'verbose_name_plural': 'Creator Profiles',
                'db_table': 'creators_profile',
                'ordering': ['-followers_count'],
            },
        ),
    ]
