# Generated by Django 6.0.1 on 2026-04-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_creatorprofile_is_early_adopter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creatorprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Creator Profile', 'verbose_name_plural': 'Creator Profiles'},
        ),
    ]
