# Generated by Django 6.0.1 on 2026-04-17 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('ZMW', 'Zambian Kwacha'), ('EUR', 'Euro')], max_length=3)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('captured', 'Captured'), ('partially_captured', 'Partially Captured'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('requires_action', 'Requires Action'), ('requires_confirmation', 'Requires Confirmation'), ('disputed', 'Disputed'), ('in_reconciliation', 'IN_RECONCILIATION'), ('paid', 'Paid'), ('submitted', 'Submitted'), ('rejected', 'Rejected')], max_length=30)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('provider_request', models.JSONField(blank=True, default=dict)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('provider_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Attempt',
                'verbose_name_plural': 'Payment Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('payout_interval_days', models.PositiveIntegerField(choices=[(7, 'Weekly'), (14, 'Bi-Weekly'), (30, 'Monthly')], default=30)),
                ('level', models.CharField(default='BASIC', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='creators.creatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WalletKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document_type', models.CharField(choices=[('NRC', 'National Registration Card'), ('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', 'Drivers License'), ('VOTERS_CARD', 'Voters Card')], max_length=20)),
                ('id_document_number', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_document_copy', models.FileField(blank=True, null=True, upload_to='kyc_ids/')),
                ('pacra_certificate_copy', models.FileField(blank=True, null=True, upload_to='kyc_certificates/')),
                ('tax_certificate_copy', models.FileField(blank=True, null=True, upload_to='kyc_certificates/')),
                ('account_type', models.CharField(choices=[('BANK', 'BANK'), ('MOBILE_MONEY', 'MOBILE_MONEY')], default='MOBILE_MONEY', max_length=20)),
                ('bank_name', models.CharField(help_text='Prefered bank/mobile money to receive funds', max_length=200)),
                ('bank_account_name', models.CharField(help_text='Names on your bank account', max_length=200)),
                ('bank_account_number', models.CharField(help_text='Bank ot Mobile money account number', max_length=200)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='wallets.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletPayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MTN_MOMO_ZMB', 'MTN'), ('AIRTEL_OAPI_ZMB', 'Airtel'), ('ZAMTEL_ZMB', 'Zamtel')], max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to='wallets.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('CASH_IN', 'Cash In'), ('PAYOUT', 'Payout'), ('REVERSAL', 'Reversal'), ('FEE', 'Fee')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('correlation_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_fees', to='wallets.wallettransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('warning_needs_response', 'Warning Needs Response'), ('needs_response', 'Needs Response'), ('under_review', 'Under Review'), ('won', 'Won'), ('lost', 'Lost'), ('charge_refunded', 'Charge Refunded')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('ZMW', 'Zambian Kwacha'), ('EUR', 'Euro')], max_length=3)),
                ('initiated_at', models.DateTimeField()),
                ('due_by', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('communication', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(choices=[('MTN_MOMO_ZMB', 'MTN ZAMBIA'), ('AIRTEL_OAPI_ZMB', 'AIRTEL MONEY ZAMBIA'), ('ZAMTEL_ZMB', 'ZAMTEL KWACHA')], max_length=30)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'indexes': [models.Index(fields=['payment', 'status'], name='wallets_dis_payment_879878_idx'), models.Index(fields=['external_id', 'provider'], name='wallets_dis_externa_0ba159_idx')],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('ZMW', 'Zambian Kwacha'), ('EUR', 'Euro')], max_length=3)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('provider', models.CharField(choices=[('MTN_MOMO_ZMB', 'MTN ZAMBIA'), ('AIRTEL_OAPI_ZMB', 'AIRTEL MONEY ZAMBIA'), ('ZAMTEL_ZMB', 'ZAMTEL KWACHA')], max_length=30)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_records', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'indexes': [models.Index(fields=['payment', 'status'], name='wallets_ref_payment_c95341_idx'), models.Index(fields=['external_id', 'provider'], name='wallets_ref_externa_423ada_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
    ]
