# Generated by Django 6.0.1 on 2026-02-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('wallets', '0005_remove_walletkyc_full_name_walletkyc_account_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='wallets_pay_referen_ef82d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='wallets_pay_patron__ddd25b_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='wallets_pay_order_r_8e861c_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='wallets_pay_provide_b354d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='wallets_pay_created_2529d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='wallets_pay_amount_87c5a7_idx',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='amount_captured_lte_amount',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='amount_refunded_lte_amount_captured',
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='paymentwebhooklog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_records', to='payments.payment'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
