# Generated by Django 6.0.1 on 2026-02-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='provider',
            field=models.CharField(choices=[('MTN_MOMO_ZMB', 'MTN ZAMBIA'), ('AIRTEL_OAPI_ZMB', 'AIRTEL MONEY ZAMBIA'), ('ZAMTEL_ZMB', 'ZAMTEL KWACHA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentwebhooklog',
            name='provider',
            field=models.CharField(choices=[('MTN_MOMO_ZMB', 'MTN ZAMBIA'), ('AIRTEL_OAPI_ZMB', 'AIRTEL MONEY ZAMBIA'), ('ZAMTEL_ZMB', 'ZAMTEL KWACHA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='refund',
            name='provider',
            field=models.CharField(choices=[('MTN_MOMO_ZMB', 'MTN ZAMBIA'), ('AIRTEL_OAPI_ZMB', 'AIRTEL MONEY ZAMBIA'), ('ZAMTEL_ZMB', 'ZAMTEL KWACHA')], max_length=30),
        ),
    ]
