# Generated by Django 6.0.1 on 2026-01-28 18:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('client_type', models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile Application'), ('internal', 'Internal Service'), ('partner', 'Partner API')], max_length=20)),
                ('api_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit', models.IntegerField(default=1000, help_text='Requests per hour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Client',
                'verbose_name_plural': 'API Clients',
                'db_table': 'auth_apiclient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('creator', 'Creator'), ('admin', 'Admin'), ('staff', 'Staff')], default='creator', max_length=20),
        ),
    ]
