# Generated by Django 6.0.1 on 2026-01-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_apiclient_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
