# Generated by Django 6.0.1 on 2026-04-17 07:40

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(help_text='reference for patron-facing purposes', max_length=100)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Payment ID from the payment provider', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in the specified currency', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('ZMW', 'Zambian Kwacha'), ('EUR', 'Euro')], default='ZMW', max_length=3)),
                ('amount_captured', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount successfully captured', max_digits=20)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount refunded to patron', max_digits=20)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('captured', 'Captured'), ('partially_captured', 'Partially Captured'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('requires_action', 'Requires Action'), ('requires_confirmation', 'Requires Confirmation'), ('disputed', 'Disputed'), ('in_reconciliation', 'IN_RECONCILIATION'), ('paid', 'Paid'), ('submitted', 'Submitted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=30)),
                ('provider', models.CharField(choices=[('MTN_MOMO_ZMB', 'MTN ZAMBIA'), ('AIRTEL_OAPI_ZMB', 'AIRTEL MONEY ZAMBIA'), ('ZAMTEL_ZMB', 'ZAMTEL KWACHA')], db_index=True, max_length=30)),
                ('patron_phone', models.CharField(help_text='Zambia standard 10 digit mobile number', max_length=12)),
                ('patron_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('patron_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patron_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Fee charged by the payment provider', max_digits=20, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount after provider fees', max_digits=20, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_reference', models.CharField(blank=True, max_length=255)),
                ('provider_data', models.JSONField(blank=True, default=dict, help_text='Raw response data from payment provider')),
                ('provider_metadata', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('risk_score', models.FloatField(blank=True, help_text='Risk assessment score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('requires_3ds', models.BooleanField(default=False)),
                ('redirect_url', models.URLField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('callback_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('MTN_MOMO_ZMB', 'MTN ZAMBIA'), ('AIRTEL_OAPI_ZMB', 'AIRTEL MONEY ZAMBIA'), ('ZAMTEL_ZMB', 'ZAMTEL KWACHA')], max_length=30)),
                ('event_type', models.CharField(choices=[('deposit.initiated', 'Deposit Initiated'), ('deposit.accepted', 'Deposit Accepted'), ('deposit.completed', 'Deposit Completed'), ('deposit.failed', 'Deposit Failed'), ('deposit.callback_received', 'Deposit Callback Received')], db_index=True, default='deposit.accepted', max_length=200)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('raw_payload', models.TextField(help_text='Raw webhook payload')),
                ('parsed_payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_ms', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Webhook Log',
                'verbose_name_plural': 'Payment Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
