# Generated by Django 6.0.1 on 2026-04-17 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wallets.wallet'),
        ),
        migrations.AddField(
            model_name='paymentwebhooklog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.payment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference', 'status'], name='payments_pa_referen_e9ad27_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patron_phone', 'created_at'], name='payments_pa_patron__63d318_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at', 'status'], name='payments_pa_created_bc9e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['amount', 'currency'], name='payments_pa_amount_e7ee9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_captured__lte', models.F('amount'))), name='amount_captured_lte_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_refunded__lte', models.F('amount_captured'))), name='amount_refunded_lte_amount_captured'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhooklog',
            index=models.Index(fields=['provider', 'event_type'], name='payments_pa_provide_ecd09e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhooklog',
            index=models.Index(fields=['created_at', 'status'], name='payments_pa_created_4c30c1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhooklog',
            index=models.Index(fields=['payment', 'created_at'], name='payments_pa_payment_6ed0d3_idx'),
        ),
    ]
