# Generated by Django 6.0.1 on 2026-02-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_isp_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='isp_provider',
            new_name='provider',
        ),
        migrations.AlterField(
            model_name='payment',
            name='patron_phone',
            field=models.CharField(help_text='Zambia standard 10 digit mobile number', max_length=12),
        ),
    ]
