# Generated by Django 6.0.1 on 2026-02-11 21:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_isp_provider_payment_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('MTN_MOMO_ZMB', 'MTN ZAMBIA'), ('AIRTEL_OAPI_ZMB', 'AIRTEL MONEY ZAMBIA'), ('ZAMTEL_ZMB', 'ZAMTEL KWACHA')], max_length=30)),
                ('event_type', models.CharField(choices=[('deposit.initiated', 'Deposit Initiated'), ('deposit.accepted', 'Deposit Accepted'), ('deposit.completed', 'Deposit Completed'), ('deposit.failed', 'Deposit Failed'), ('deposit.callback_received', 'Deposit Callback Received')], db_index=True, default='deposit.accepted', max_length=200)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('raw_payload', models.TextField(help_text='Raw webhook payload')),
                ('parsed_payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_ms', models.FloatField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Webhook Log',
                'verbose_name_plural': 'Payment Webhook Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'event_type'], name='payments_pa_provide_ecd09e_idx'), models.Index(fields=['created_at', 'status'], name='payments_pa_created_4c30c1_idx'), models.Index(fields=['payment', 'created_at'], name='payments_pa_payment_6ed0d3_idx')],
            },
        ),
    ]
